#ifndef ti_msp_dl_config_h
#define ti_msp_dl_config_h

#define CONFIG_MSPM0G350X
#define CONFIG_MSPM0G3507

#if defined(__ti_version__) || defined(__TI_COMPILER_VERSION__)
#define SYSCONFIG_WEAK __attribute__((weak))
#elif defined(__IAR_SYSTEMS_ICC__)
#define SYSCONFIG_WEAK __weak
#elif defined(__GNUC__)
#define SYSCONFIG_WEAK __attribute__((weak))
#endif

#include <ti/devices/msp/msp.h>
#include <ti/driverlib/driverlib.h>
#include <ti/driverlib/m0p/dl_core.h>
#include <stdbool.h>

#define POWER_STARTUP_DELAY 16U
#define CPUCLK_FREQ 32000000U

#define MOTOR_PWM_INST TIMG6
#define MOTOR_PWM_LEFT_IOMUX IOMUX_PINCM15
#define MOTOR_PWM_LEFT_FUNC IOMUX_PINCM15_PF_TIMG6_CCP0
#define MOTOR_PWM_LEFT_PIN DL_GPIO_PIN_2
#define MOTOR_PWM_RIGHT_IOMUX IOMUX_PINCM16
#define MOTOR_PWM_RIGHT_FUNC IOMUX_PINCM16_PF_TIMG6_CCP1
#define MOTOR_PWM_RIGHT_PIN DL_GPIO_PIN_3

#define MOTOR_DIR_PORT GPIOB
#define MOTOR_LEFT_IN1_PIN DL_GPIO_PIN_18
#define MOTOR_LEFT_IN1_IOMUX IOMUX_PINCM44
#define MOTOR_LEFT_IN2_PIN DL_GPIO_PIN_19
#define MOTOR_LEFT_IN2_IOMUX IOMUX_PINCM45
#define MOTOR_RIGHT_IN1_PIN DL_GPIO_PIN_20
#define MOTOR_RIGHT_IN1_IOMUX IOMUX_PINCM48
#define MOTOR_RIGHT_IN2_PIN DL_GPIO_PIN_24
#define MOTOR_RIGHT_IN2_IOMUX IOMUX_PINCM52

#define ENCODER_LEFT_PORT GPIOB
#define ENCODER_LEFT_A_PIN DL_GPIO_PIN_0
#define ENCODER_LEFT_A_IOMUX IOMUX_PINCM12
#define ENCODER_LEFT_B_PIN DL_GPIO_PIN_1
#define ENCODER_LEFT_B_IOMUX IOMUX_PINCM13
#define ENCODER_RIGHT_PORT GPIOB
#define ENCODER_RIGHT_A_PIN DL_GPIO_PIN_7
#define ENCODER_RIGHT_A_IOMUX IOMUX_PINCM24
#define ENCODER_RIGHT_B_PIN DL_GPIO_PIN_6
#define ENCODER_RIGHT_B_IOMUX IOMUX_PINCM23

#define LINE_L4_PIN DL_GPIO_PIN_12
#define LINE_L4_IOMUX IOMUX_PINCM34
#define LINE_L3_PIN DL_GPIO_PIN_13
#define LINE_L3_IOMUX IOMUX_PINCM35
#define LINE_L2_PIN DL_GPIO_PIN_14
#define LINE_L2_IOMUX IOMUX_PINCM36
#define LINE_L1_PIN DL_GPIO_PIN_15
#define LINE_L1_IOMUX IOMUX_PINCM37
#define LINE_R1_PIN DL_GPIO_PIN_16
#define LINE_R1_IOMUX IOMUX_PINCM38
#define LINE_R2_PIN DL_GPIO_PIN_17
#define LINE_R2_IOMUX IOMUX_PINCM39
#define LINE_R3_PIN DL_GPIO_PIN_0
#define LINE_R3_IOMUX IOMUX_PINCM1
#define LINE_R4_PIN DL_GPIO_PIN_1
#define LINE_R4_IOMUX IOMUX_PINCM2
#define LINE_SENSOR_PORT GPIOA
#define LINE_SENSOR_ALL_PINS_MASK (LINE_L4_PIN | LINE_L3_PIN | LINE_L2_PIN | LINE_L1_PIN | LINE_R1_PIN | LINE_R2_PIN | LINE_R3_PIN | LINE_R4_PIN)

#define OLED_SPI_PORT GPIOB
#define OLED_SPI_MOSI_PIN DL_GPIO_PIN_8
#define OLED_SPI_MOSI_IOMUX IOMUX_PINCM25
#define OLED_SPI_CLOCK_PIN DL_GPIO_PIN_9
#define OLED_SPI_CLOCK_IOMUX IOMUX_PINCM26
#define OLED_RESET_PIN DL_GPIO_PIN_10
#define OLED_RESET_IOMUX IOMUX_PINCM27
#define OLED_DATA_COMMAND_PIN DL_GPIO_PIN_11
#define OLED_DATA_COMMAND_IOMUX IOMUX_PINCM28
#define OLED_CHIP_SELECT_PIN DL_GPIO_PIN_14
#define OLED_CHIP_SELECT_IOMUX IOMUX_PINCM31
#define OLED_SPI_ALL_PINS_MASK (OLED_SPI_MOSI_PIN | OLED_SPI_CLOCK_PIN | OLED_RESET_PIN | OLED_DATA_COMMAND_PIN | OLED_CHIP_SELECT_PIN)

#define WIRELESS_UART_INST UART1
#define WIRELESS_UART_INT_IRQN UART1_INT_IRQn
#define WIRELESS_UART_TX_IOMUX IOMUX_PINCM19
#define WIRELESS_UART_TX_FUNC IOMUX_PINCM19_PF_UART1_TX
#define WIRELESS_UART_RX_IOMUX IOMUX_PINCM20
#define WIRELESS_UART_RX_FUNC IOMUX_PINCM20_PF_UART1_RX

#define GYRO_UART_INST UART3
#define GYRO_UART_INT_IRQN UART3_INT_IRQn
#define GYRO_UART_TX_IOMUX IOMUX_PINCM59
#define GYRO_UART_TX_FUNC IOMUX_PINCM59_PF_UART3_TX
#define GYRO_UART_RX_IOMUX IOMUX_PINCM55
#define GYRO_UART_RX_FUNC IOMUX_PINCM55_PF_UART3_RX

#define BOARD_KEY_PORT GPIOB
#define BOARD_KEY_PIN DL_GPIO_PIN_21
#define BOARD_KEY_IOMUX IOMUX_PINCM49

#define MENU_BUTTON_PORT GPIOB
#define MENU_BUTTON_UP_PIN DL_GPIO_PIN_15
#define MENU_BUTTON_UP_IOMUX IOMUX_PINCM32
#define MENU_BUTTON_DOWN_PIN DL_GPIO_PIN_16
#define MENU_BUTTON_DOWN_IOMUX IOMUX_PINCM33
#define MENU_BUTTON_BACK_PIN DL_GPIO_PIN_17
#define MENU_BUTTON_BACK_IOMUX IOMUX_PINCM43

#ifdef __cplusplus
extern "C" {
#endif
void SYSCFG_DL_init(void);
bool SYSCFG_DL_saveConfiguration(void);
bool SYSCFG_DL_restoreConfiguration(void);
#ifdef __cplusplus
}
#endif

#endif
