"""Ball-and-beam controller for the 2026 NUEDC problem H swing arm.

Camera loop = outer control loop: YOLO26 ball detection -> alpha-beta filter ->
three-level cascade (ball position -> ball velocity -> beam angular velocity)
-> one ZDT Emm frame per update over UART.

The cascade is the whole point (see cascade.py): the motor does not set the
ball's position, it sets the tilt RATE, and tilt integrates into an angle which
produces acceleration which integrates twice into position.  Commanding tilt
rate instead of tilt angle means the static tilt that fights the mechanical zero
offset is generated by the loop structure, so the ball settles ON the target
rather than a few millimetres beside it, and the acceleration-damping term
brakes the ball before it reaches the setpoint instead of after.

Modes:
  IDLE       motor untouched, detection + display only
  HOLD       cascade keeps the ball at the beam center O (target 0 cm)
  TASK3      contest task 3: O -> +5 cm, turn around, -> -5 cm and settle
  SAFE_LOST  ball lost too long: beam ramps back to level until it returns

TASK3 runs on its OWN controller and its OWN parameter file (task3_ctrl.py +
task3_config.py -> /root/task3_config.json); HOLD and SAFE_LOST run on
cascade.py + the CONFIG below -> /root/ctrl_config.json.  The two never share a
gain, so tuning HOLD cannot move TASK3 and vice versa.  Their closed-loop laws
now use the same fast velocity estimate, braking cap, and far/near gain shape;
only their state, targets, and parameter values stay independent.  The tune
page's PAGE button switches between them.  The exceptions are wiring/mechanical facts
(direction, travel limit) which are mirrored one-way from here -- see
task3_config.MIRRORED_FROM_MAIN for why two copies of those is a trap.

Startup assumption: the beam is level at power-on; the motor position register
is cleared then (set_zero), so 0 deg always means level.
"""

import os

from maix import camera, display, image, nn, app, time, sys, uart, touchscreen

from ball_position import (
    AdaptiveAlphaBetaFilter,
    axis_point,
    position_from_pixel,
    validate_calibration,
)
from zdt_motor import ZdtEmmMotor
from cascade import CascadeController
from task3_ctrl import Task3Controller, Task3FSM
from board_light import BoardLight
import task3_config as t3cfg
import ctrl_ui

# ==================== CONFIG ====================

# Actuator gains are in MOTOR degrees, not beam degrees.  KV/KA follow the crank
# ratio, not the configured travel limit; tightening max_motor_deg must not also
# starve the velocity loop by shrinking its gains.
#
# Sign convention: CascadeController.update (`omega *= dir_sign`) is the single
# flip, fed from dir_invert.  Never add a
# second negation anywhere else -- two flips read as "correct" in isolation and
# cancel, which is unfindable.  This rig runs dir_invert = 0.
CONFIG = {
    # --- low-latency ball speed (same method as TASK3 final hold) ---
    "v_from_pos": 1,       # 1 = differentiate filtered position; 0 = alpha-beta vx
    "v_lpf": 0.70,         # short LPF after differentiation
    # --- level 3: ball position outer loop + braking cap (cm -> cm/s) ---
    "kp_far": 1.50,
    "kp_near": 1.50,
    "near_band_cm": 2.0,
    "ki_x": 0.0,          # keep 0: theta = integral(omega) already trims offset
    "i_lim_cms": 3.0,
    "i_zone_cm": 2.0,
    "v_max_cms": 12.0,
    "v_floor_cms": 3.0,   # final correction authority under the braking cap
    "a_brake_cms2": 16.0, # lower if return overshoots; raise if it brakes too early
    # --- level 2: ball velocity loop + accel damping (cm/s -> motor deg/s) ---
    # These follow the crank ratio (~3 motor deg per beam deg), NOT the travel
    # limit: shrinking them along with max_motor_deg starves the velocity loop.
    # Offline, 1.4/0.45 pushed overshoot from 0.2 cm to 2.7 cm and cost 0.7 s.
    "kv_far": 4.4,
    "kv_near": 4.4,
    "ka_far": 1.5,
    "ka_near": 1.5,       # lead term: brakes before the setpoint, not after
    "a_lpf": 0.50,
    "a_max_cms2": 200.0,
    "omega_max_dps": 90.0,
    # --- level 1: actuator ---
    # These start deliberately TAME.  MaixCAM2 runs off its internal battery, and
    # a stalled motor at high rpm browns the battery out and resets the board, so
    # travel and speed stay small until the rig is calibrated (README step 2).
    # Measured on the rig by probe.py, not chosen: a 4 deg staircase needed +20
    # deg before the ball broke away on the + side and -4 deg on the - side, so
    # 12 deg of travel could not steer this beam at all.  30/240/0 are also the
    # values the flat-PID version ran with here.
    "max_motor_deg": 30.0,   # crank travel limit, calibrate on the rig!
    "soft_frac": 0.75,       # soft-limit starts at 75% of travel
    "drive_mode": 0,         # 0 = absolute position (default), 1 = velocity mode
    "motor_rpm": 240,        # rpm ceiling for the per-frame absolute move
    "rpm_min": 8,
    "motor_acc": 0,          # 0 = direct start; a ramp only adds lag here
    # 0 per the operator watching the rig, which overrides the probe reading.
    # The open-loop staircase did record the ball running +4.05 -> +1.57 cm at
    # theta = +20 deg, but that was the run whose stall took the driver offline,
    # so the beam's zero may already have been off level and an impulse-driven
    # roll is not evidence about the steady-state direction.  Recheck with one
    # HOLD run once the driver answers again: ball right of centre must drive
    # theta the way that brings it back, not into the travel limit.
    "dir_invert": 0,         # flip if the beam tilts the wrong way
    "relax_dps": 25.0,       # rate the beam returns to level on ball loss
    "pos_poll_ms": 0,        # 0 = never send 0x36 (this firmware answers EE)
    # --- ball end guard ---
    "x_ref_max_cm": 10.0,    # targets are clipped into the safe span
    "x_guard_cm": 10.0,      # fade out speed commands past this point
    # (task 3's gains and timing live in task3_config.py, not here)
    # --- display ---
    # Draw + disp.show only every Nth frame.  The motor command goes out well
    # before the draw block, so everything skipped here delays the NEXT capture
    # and nothing else: the control rate goes up and the measurement latency
    # does not move.  1 = every frame (old behaviour).  Raise it only after
    # CTRL_PROF=1 shows the ui column is actually worth something; on a rig where
    # the NPU dominates this buys nothing and just makes the screen choppy.
    "draw_every": 1,
    # --- safety / detection ---
    "lost_timeout_ms": 500,
    "stuck_err_cm": 1.5,
    "stuck_v_cms": 0.5,
    "stuck_ms": 1500,
    "conf_th": 0.70,
}

# Gain symbols (KP/KI/KV/KA) stay Latin -- that is what they are called in the
# reference and on paper.  Everything else gets a Chinese label so it is readable
# at a glance on the rig.  The Chinese column is only used if a CJK font loads
# (see ctrl_ui.init_cjk_font); otherwise the English column is used, because
# MaixPy draws missing glyphs as empty boxes.
_PARAM_TABLE = (
    # english, chinese, path, step, low, high
    ("V SRC",     "球速来源",      ("v_from_pos",),     1,    0,   1),
    ("V LPF",     "球速滤波",      ("v_lpf",),          0.05, 0.05, 1.0),
    ("KV FAR",    "KV 远",        ("kv_far",),         0.1,  0.0, 30.0),
    ("KV NEAR",   "KV 近",        ("kv_near",),        0.1,  0.0, 30.0),
    ("KA FAR",    "KA 远",        ("ka_far",),         0.05, 0.0, 10.0),
    ("KA NEAR",   "KA 近",        ("ka_near",),        0.05, 0.0, 10.0),
    ("A LPF",     "加速度滤波",   ("a_lpf",),          0.05, 0.05, 1.0),
    ("W MAX",     "最大角速度",    ("omega_max_dps",),  5.0,  5.0, 600.0),
    ("KP FAR",    "KP 远",        ("kp_far",),         0.1,  0.0, 10.0),
    ("KP NEAR",   "KP 近",        ("kp_near",),        0.1,  0.0, 10.0),
    ("NEAR BAND", "远近分界",      ("near_band_cm",),   0.5,  0.5, 8.0),
    ("V MAX",     "最大球速",      ("v_max_cms",),      0.5,  1.0, 40.0),
    ("A BRAKE",   "制动减速度",    ("a_brake_cms2",),   1.0,  2.0, 120.0),
    ("V FLOOR",   "最低限速",      ("v_floor_cms",),    0.5,  0.5, 10.0),
    ("MAX DEG",   "行程限幅",      ("max_motor_deg",),  1.0,  2.0, 90.0),
    ("SOFT FRC",  "软限位起点",    ("soft_frac",),      0.05, 0.3, 1.0),
    ("DIR INV",   "方向反转",      ("dir_invert",),     1,    0,   1),
    ("DRIVE MD",  "驱动模式",      ("drive_mode",),     1,    0,   1),
    ("KI X",      "KI X",         ("ki_x",),           0.01, 0.0, 2.0),
    ("I LIM",     "积分限幅",      ("i_lim_cms",),      0.5,  0.0, 10.0),
    ("I ZONE",    "积分区间",      ("i_zone_cm",),      0.5,  0.5, 12.5),
    ("RPM MAX",   "最大转速",      ("motor_rpm",),      10,   30,  1000),
    ("RPM MIN",   "最小转速",      ("rpm_min",),        1,    1,   100),
    ("ACC",       "加减速档",      ("motor_acc",),      5,    0,   255),
    ("RELAX DPS", "丢球回位速度",  ("relax_dps",),      5.0,  5.0, 200.0),
    ("STUCK MS",  "卡球判定",      ("stuck_ms",),       100,  300, 5000),
    ("LOST MS",   "丢球判定",      ("lost_timeout_ms",), 50,  200, 2000),
    ("CONF",      "置信度",        ("conf_th",),        0.05, 0.1, 0.95),
    ("DRAW EVRY", "画面分频",      ("draw_every",),     1,    1,   5),
    ("POS POLL",  "位置回读",      ("pos_poll_ms",),    25,   0,   500),
)

USE_CN_LABELS = ctrl_ui.init_cjk_font()
TUNABLE_PARAMS = tuple(
    ((cn if USE_CN_LABELS else en), path, step, low, high)
    for en, cn, path, step, low, high in _PARAM_TABLE
)
# TASK3's table is flat (its config has no nesting), so wrap each key as a
# one-element path to match the shape ctrl_ui walks.
TASK3_PARAMS = tuple(
    ((cn if USE_CN_LABELS else en), (key,), step, low, high)
    for en, cn, key, step, low, high in t3cfg.PARAM_TABLE
)

CONFIG_FILE = "/root/ctrl_config.json"
# bump whenever the default gains change scale, so a file saved against the old
# defaults is discarded instead of silently restoring aggressive values
# v5: HOLD adopts TASK3-style fast velocity, braking cap, and far/near gains.
CONFIG_VERSION = 5
AUTO_ZERO_ON_BOOT = True

DEBUG_LOG = False

# Tuning instrumentation, off unless the environment asks for it, so the app the
# operator launches from the menu behaves exactly as before.  One CSV row per
# frame is the only way to tell "the gains are wrong" from "the ball estimate is
# noisy" or "the loop is running at 12 fps" -- on-screen numbers move too fast to
# read and average out the very transients being tuned.
TELEMETRY = os.environ.get("CTRL_TELEM", "0") == "1"
# Per-stage frame budget, printed once a second.  The status bar only ever shows
# the total, and "we are at 18 fps" does not say whether to attack the camera,
# the NPU or the screen -- three fixes with completely different costs.  Every
# stopwatch call is behind this flag, so the default path is byte-for-byte the
# old loop.
PROFILE = os.environ.get("CTRL_PROF", "0") == "1"
# "hold" starts the position loop without an on-screen tap, so an unattended
# timed run still records a step response.  Empty means idle until tapped.
AUTOSTART = os.environ.get("CTRL_AUTOSTART", "").strip().lower()

LOW_LATENCY_MODE = True
MIN_FRAME_HEIGHT = 180
DETECTION_ROI_HEIGHT = 170

# beam axis: +/-12.5 cm around the center O (contest coordinate frame)
AXIS_START_CM = -12.5
AXIS_END_CM = 12.5

MAIXCAM_MODEL_PATH = "models/yolo26_all_maixcam_yolo26_480_160/yolo26_all.mud"
MAIXCAM2_MODEL_PATH = "models/my_ball_maixcam2/best.mud"


def print_debug(s):
    if DEBUG_LOG:
        print(s)


# ==================== init ====================

ctrl_ui.load_config(CONFIG, TUNABLE_PARAMS, CONFIG_FILE, CONFIG_VERSION)
t3cfg.load_runtime()
t3cfg.apply_env_overrides()


def apply_env_overrides():
    """CTRL_OVERRIDE="kv_far=3.0,max_motor_deg=6" -- one tuning run, no file edit.

    Applied after load_config so a probe run wins over the saved file, and only
    for keys that already exist, so a typo is reported instead of quietly adding
    a config entry nothing reads.
    """
    spec = os.environ.get("CTRL_OVERRIDE", "").strip()
    if not spec:
        return
    for item in spec.split(","):
        if not item.strip():
            continue
        key, _, raw = item.partition("=")
        key = key.strip()
        if key not in CONFIG:
            print("override: unknown key", key)
            continue
        old = CONFIG[key]
        try:
            CONFIG[key] = int(raw) if isinstance(old, int) else float(raw)
        except ValueError:
            print("override: bad value for", key, raw)
            continue
        print("override: {} {} -> {}".format(key, old, CONFIG[key]))


apply_env_overrides()


def model_path_for_device(device_name):
    normalized_name = device_name.strip().lower()
    if normalized_name == "maixcam2":
        return MAIXCAM2_MODEL_PATH
    if normalized_name in ("maixcam", "maixcam-pro", "maixcam_pro"):
        return MAIXCAM_MODEL_PATH
    raise ValueError("unsupported device: {}".format(device_name))


detector = nn.YOLO26(
    model=model_path_for_device(sys.device_name()),
    dual_buff=not LOW_LATENCY_MODE,
)

FRAME_WIDTH = detector.input_width()
FRAME_HEIGHT = max(detector.input_height(), MIN_FRAME_HEIGHT)
DETECTION_ROI_X = 0
DETECTION_ROI_Y = (FRAME_HEIGHT - DETECTION_ROI_HEIGHT) // 2
DETECTION_ROI_WIDTH = FRAME_WIDTH
AXIS_START_PX = (5, FRAME_HEIGHT // 2)
AXIS_END_PX = (FRAME_WIDTH - 5, FRAME_HEIGHT // 2)
AXIS_LEN_PX = AXIS_END_PX[0] - AXIS_START_PX[0]

validate_calibration(AXIS_START_PX, AXIS_END_PX, AXIS_START_CM, AXIS_END_CM,
                     FRAME_WIDTH, FRAME_HEIGHT)

# The crop handed to detect() should be exactly the model's input size.  Any
# other size makes the runtime rescale it on every single frame -- a cost that
# is invisible from the fps number and that also resamples the ball, so it is
# not only slower but slightly less accurate.  DETECTION_ROI_HEIGHT is a hand
# -picked constant, so say out loud when it does not line up rather than let it
# rot silently.
if DETECTION_ROI_HEIGHT != detector.input_height():
    print("detect: 模型输入 {}x{}，裁剪 {}x{} -> 每帧多一次内部缩放。"
          "把 DETECTION_ROI_HEIGHT 改成 {} 可以省掉（会少看 {} 行像素，"
          "确认球不会跑出这个带）".format(
              detector.input_width(), detector.input_height(),
              DETECTION_ROI_WIDTH, DETECTION_ROI_HEIGHT,
              detector.input_height(),
              DETECTION_ROI_HEIGHT - detector.input_height()))
else:
    print("detect: 裁剪 {}x{} 正好等于模型输入，无缩放".format(
        DETECTION_ROI_WIDTH, DETECTION_ROI_HEIGHT))

cam = camera.Camera(FRAME_WIDTH, FRAME_HEIGHT, detector.input_format())
disp = display.Display()
ts = touchscreen.TouchScreen()
position_filter = AdaptiveAlphaBetaFilter()

# MaixCAM2: route pins B0/B1 to UART2 (/dev/ttyS2) for the motor bus.
UART_DEVICE = "/dev/ttyS2"
UART_TX_PIN, UART_TX_FUNC = "B0", "UART2_TX"
UART_RX_PIN, UART_RX_FUNC = "B1", "UART2_RX"

from maix import err
try:
    from maix.peripheral import pinmap
except ImportError:
    from maix import pinmap
err.check_raise(pinmap.set_pin_function(UART_TX_PIN, UART_TX_FUNC),
                "failed to set motor UART TX pin")
err.check_raise(pinmap.set_pin_function(UART_RX_PIN, UART_RX_FUNC),
                "failed to set motor UART RX pin")
print("uart devices:", uart.list_devices())
serial = uart.UART(UART_DEVICE, 115200)
motor = ZdtEmmMotor(serial, addr=0x01, max_abs_deg=CONFIG["max_motor_deg"])

# Onboard illumination LED, toggled by the LIGHT button.  Detection quality is
# the outer loop's sensor, so being able to add light without leaving the app is
# worth a button.  Off at startup: it shares the battery whose brownout resets
# the board, and the model was trained under whatever light the rig already has.
light = BoardLight(on_at_start=False)

ctrl = CascadeController(CONFIG)      # HOLD / SAFE_LOST
t3 = Task3Controller()                # TASK3 only, reads t3cfg.CONFIG live
fsm = Task3FSM()
ui = ctrl_ui.CtrlUI((("MAIN", CONFIG, TUNABLE_PARAMS),
                     ("TASK3", t3cfg.CONFIG, TASK3_PARAMS)),
                    FRAME_WIDTH, FRAME_HEIGHT, disp, ts)
ui.set_button_on("LIGHT", light.is_on)

# USER/OK key quits the program.  rm_default_listener is still required, and
# now for the opposite reason to before: the system default handler tears the
# app down where it stands, so the shutdown block at the bottom of this file
# never runs and the beam drops -- which rolls the ball off the rig after a
# TASK3 run.  Taking the key ourselves means the exit goes through that block.
# View switching lives on the TUNE / BACK buttons, which already cover it.
maix_key = None
user_key = None
try:
    from maix.peripheral import key as maix_key
    try:
        maix_key.rm_default_listener()
    except Exception:
        pass
    user_key = maix_key.Key()
except Exception as e:
    print("key module unavailable:", e)


def key_exit_pressed():
    if user_key is None:
        return False
    try:
        key_id, state = user_key.read()
        pressed = getattr(maix_key.State, "KEY_PRESSED", 1)
        return state == pressed and key_id != 0
    except Exception:
        return False


def sync_ctrl_from_config():
    ctrl.sync(CONFIG)
    # Direction and travel are facts about the machine, not tuning choices, so
    # they have exactly one editable copy (the MAIN page) and are mirrored into
    # TASK3's config one-way.  Two independent copies means one of them is
    # always stale, and a stale dir_invert does not merely control badly: the
    # beam drives the ball the wrong way, pins itself against the travel stop
    # and stalls, which browns the battery out and resets the board.
    for key in t3cfg.MIRRORED_FROM_MAIN:
        t3cfg.CONFIG[key] = CONFIG[key]
    motor.max_abs_deg = CONFIG["max_motor_deg"]


def drive_motor(theta_deg, omega_dps, now_ms, cfg):
    """Hand a controller's output to the driver in whichever mode it selected.

    cfg is the active mode's config: TASK3 carries its own drive_mode/rpm/acc so
    it can be driven harder than HOLD without touching HOLD's settings.
    """
    if cfg["drive_mode"]:
        motor.move_vel_dps(omega_dps, cfg["motor_acc"], now_ms)
    else:
        rpm = motor.rpm_for_dps(omega_dps, cfg["rpm_min"], cfg["motor_rpm"])
        motor.move_abs_deg(theta_deg, rpm, cfg["motor_acc"], now_ms)


def release_motor():
    """Leave a closed-loop mode: velocity mode would otherwise keep spinning."""
    motor.stop_now()


# Bright yellow: the axis is the operator's reference for where the ball
# actually is, so it has to read at a glance against the beam and the bench.
# The centre mark goes white -- a yellow cross on a yellow line is invisible,
# and the centre is where the ball has to be placed before a run.
axis_color = image.Color.from_rgb(255, 255, 0)
zero_color = image.COLOR_WHITE


def draw_axis_and_targets(img, target_cm):
    img.draw_line(AXIS_START_PX[0], AXIS_START_PX[1],
                  AXIS_END_PX[0], AXIS_END_PX[1], axis_color, 2)
    zero_ratio = (0.0 - AXIS_START_CM) / (AXIS_END_CM - AXIS_START_CM)
    zx, zy = axis_point(zero_ratio, AXIS_START_PX, AXIS_END_PX)
    img.draw_cross(int(zx), int(zy), zero_color, 9, 2)
    t_ratio = (target_cm - AXIS_START_CM) / (AXIS_END_CM - AXIS_START_CM)
    tx, ty = axis_point(t_ratio, AXIS_START_PX, AXIS_END_PX)
    img.draw_cross(int(tx), int(ty), image.COLOR_RED, 9, 2)


def hand_over_theta(dst, src_theta):
    """Switch controllers without moving the beam.

    Each controller integrates its own theta_cmd, so entering a mode without
    seeding it from the beam's current command would make the very next absolute
    frame slam the beam by the whole difference.
    """
    dst.reset(theta_deg=src_theta)


def active_theta():
    return t3.theta_cmd if mode == "TASK3" else ctrl.theta_cmd


# ==================== main loop ====================

mode = "IDLE"
target_cm = 0.0
motor_out_deg = 0.0
omega_out_dps = 0.0
lost_ms = 0.0
safe_recover_since = None
alarm = ""   # latched faults, cleared only by a mode button
warn = ""    # live state, recomputed every frame

sync_ctrl_from_config()   # push the mirrored keys into TASK3 before anything runs

motor.enable(True)
time.sleep_ms(50)
if AUTO_ZERO_ON_BOOT:
    motor.set_zero()
    ctrl.reset(theta_deg=0.0)
    t3.reset(theta_deg=0.0)
print("motor enabled, zero set. frame:", FRAME_WIDTH, FRAME_HEIGHT,
      "uart:", UART_DEVICE)
print("task3 gains: kv={}/{} ka={}/{} vmax={} abrake={} (file {})".format(
    t3cfg.CONFIG["kv_far"], t3cfg.CONFIG["kv_near"],
    t3cfg.CONFIG["ka_far"], t3cfg.CONFIG["ka_near"],
    t3cfg.CONFIG["v_max_cms"], t3cfg.CONFIG["a_brake_cms2"],
    t3cfg.RUNTIME_FILE))


def check_motor_link(timeout_ms=400):
    """Did the driver answer anything at all?  Returns True if a frame came back.

    Worth its own check because a dead RX line is indistinguishable from bad
    gains once the loop is running: the beam never moves, the ball never
    responds, and no fault is raised -- e2/ee stay 0 precisely BECAUSE nothing
    is being received.  A whole tuning session was spent on that mistake.

    0xF3 (enable) is used as the ping since it is idempotent and this firmware
    rejects the 0x36 position read.
    """
    before = motor.rx_count
    motor.enable(True)
    t_end = time.ticks_ms() + timeout_ms
    while time.ticks_ms() < t_end:
        motor.poll()
        if motor.rx_count > before:
            return True
        time.sleep_ms(10)
    return False


MOTOR_LINK_OK = check_motor_link()
if not MOTOR_LINK_OK:
    print("WARNING: motor driver did not answer -- check 24V power, the "
          "driver's RX/TX wiring and its address. Commands are being sent "
          "into the void; no gain change can help.")

if AUTOSTART in ("hold", "task3"):
    mode = "HOLD" if AUTOSTART == "hold" else "TASK3"
    if mode == "TASK3":
        fsm.start()
        t3.reset(theta_deg=ctrl.theta_cmd)
    else:
        ctrl.reset()
    print("autostart mode:", mode)

if TELEMETRY:
    print("CFG " + " ".join(
        "{}={}".format(k, CONFIG[k]) for k in (
            "v_from_pos", "v_lpf", "kp_far", "kp_near", "ki_x",
            "v_max_cms", "a_brake_cms2", "kv_far", "kv_near",
            "ka_far", "ka_near", "a_lpf", "omega_max_dps",
            "max_motor_deg", "soft_frac", "drive_mode", "motor_rpm", "rpm_min",
            "motor_acc", "dir_invert", "conf_th")))
    print("T,ms,mode,dt_ms,target_cm,pos_cm,v_ctrl_cms,v_ref_cms,omega_dps,"
          "theta_deg,a_est,limited,tx,e2,ee,rx")

telem_t0 = None
last_ms = time.ticks_ms()
loop_ms = 1000
# CTRL_PROF=1 accumulators.  Averaged over a whole second and printed once,
# because a per-frame print costs more than the stages being measured.
prof = {"n": 0, "cam": 0, "det": 0, "ctl": 0, "ui": 0, "since": last_ms}
frame_no = 0

try:
    while not app.need_exit():
        now_ms = time.ticks_ms()
        loop_ms = now_ms - last_ms
        last_ms = now_ms
        dt = max(0.005, min(0.1, loop_ms / 1000.0))
        # a driver that never answers outranks every other live warning: with the
        # bus one-way the beam does not move and the loop looks mistuned instead
        # of unplugged
        warn = "" if (MOTOR_LINK_OK or motor.rx_count) else "DRIVER NO REPLY"

        frame_no += 1
        # Frame skipping decides only whether pixels get pushed, never what the
        # controller or the fault latches do.  Anything with a side effect must
        # stay outside every `if draw_now` -- OUT OF SPEC used to be raised
        # inside the draw block, and gating that would have quietly stopped it
        # latching, turning a failed run into a clean-looking one.
        draw_now = (frame_no % max(1, int(CONFIG["draw_every"]))) == 0
        img = cam.read()
        t_prof = time.ticks_ms() if PROFILE else 0
        if PROFILE:
            prof["cam"] += t_prof - now_ms

        detection_img = img.crop(DETECTION_ROI_X, DETECTION_ROI_Y,
                                 DETECTION_ROI_WIDTH, DETECTION_ROI_HEIGHT)
        objs = detector.detect(detection_img, conf_th=CONFIG["conf_th"],
                               iou_th=0.45)
        del detection_img
        if PROFILE:
            t_now = time.ticks_ms()
            prof["det"] += t_now - t_prof
            t_prof = t_now
        objs = [o for o in objs if o.score >= CONFIG["conf_th"]]
        ball = max(objs, key=lambda o: o.score) if objs else None

        pos_cm = None
        v_cms = 0.0
        if ball is not None:
            bx = DETECTION_ROI_X + ball.x
            by = DETECTION_ROI_Y + ball.y
            fx, fy = position_filter.update(bx + ball.w * 0.5,
                                            by + ball.h * 0.5, now_ms)
            pos_cm, _ratio, _d = position_from_pixel(
                (fx, fy), AXIS_START_PX, AXIS_END_PX,
                AXIS_START_CM, AXIS_END_CM)
            v_cms = position_filter.vx * 25.0 / AXIS_LEN_PX
            lost_ms = 0.0
            if draw_now:
                img.draw_rect(bx, by, ball.w, ball.h,
                              color=image.COLOR_GREEN, thickness=2)
        else:
            position_filter.mark_missing(now_ms)
            lost_ms += loop_ms

        # ---------- UI input ----------
        if key_exit_pressed():
            print("USER key pressed -> exit")
            try:
                app.set_exit_flag(True)
            except Exception:
                pass
            break
        action = ui.read_action()
        if action == "hold":
            hand_over_theta(ctrl, active_theta())
            fsm.stop()
            mode = "HOLD"
            alarm = ""
        elif action == "task3":
            if mode == "TASK3" and fsm.state == Task3FSM.READY:
                # second press = go.  Restarting the FSM here instead would
                # throw away the trim the ARM stage just spent seconds
                # measuring, which is the entire point of arming first.
                fsm.confirm_start()
            else:
                hand_over_theta(t3, active_theta())
                fsm.start()
                mode = "TASK3"
                alarm = ""
        elif action == "stop":
            release_motor()
            fsm.stop()
            ctrl.reset()
            mode = "IDLE"
        elif action == "zero":
            motor.set_zero()
            # the register is now 0, so the commanded angle must be 0 too or the
            # next absolute frame would slam the beam by the old offset -- both
            # controllers, since either one may be the next to command
            ctrl.reset(theta_deg=0.0)
            t3.reset(theta_deg=0.0)
            # level just moved, so every balance angle collected against the old
            # zero is now wrong.  This is the only thing that invalidates the
            # trim window -- plain reset() must not clear it, or handing over to
            # TASK3 would throw away the estimate HOLD just spent 2 s building.
            t3.reset_trim()
        elif action == "light":
            # deliberately does not touch mode/alarm: the lamp is an aid to the
            # detector, not part of the control state
            light.toggle()
            ui.set_button_on("LIGHT", light.is_on)
            if not light.available:
                print("LIGHT pressed but the LED is unavailable:", light.reason)
        elif action == "save":
            # each page owns its own file; SAVE writes both so the operator
            # never has to remember which page they were on
            ctrl_ui.save_config(CONFIG, TUNABLE_PARAMS, CONFIG_FILE, CONFIG_VERSION)
            t3cfg.save_runtime()
            ui.mark_saved(now_ms)
        sync_ctrl_from_config()

        # Off by default (pos_poll_ms = 0): this firmware answers 0x36 with EE.
        # theta_cmd is authoritative, so the readback is telemetry only.
        motor.maybe_request_position(now_ms, CONFIG["pos_poll_ms"])

        # ---------- mode arbitration ----------
        lost = lost_ms > CONFIG["lost_timeout_ms"]
        # DONE is exempt: the task requires the ball to stay at -5 cm, and
        # relaxing to level would let it roll away.  A ball sitting still at the
        # end of a run is also the case the detector is most likely to drop, so
        # treating that as "lost" would undo the run it just finished.
        if lost and (mode == "HOLD"
                     or (mode == "TASK3" and fsm.state != Task3FSM.DONE)):
            hand_over_theta(ctrl, active_theta())
            fsm.stop()
            mode = "SAFE_LOST"
            safe_recover_since = None

        if mode == "SAFE_LOST":
            st = ctrl.relax(dt)
            motor_out_deg = st["theta_cmd"]
            omega_out_dps = st["omega_dps"]
            drive_motor(motor_out_deg, omega_out_dps, now_ms, CONFIG)
            if pos_cm is not None and abs(v_cms) < 2.0:
                if safe_recover_since is None:
                    safe_recover_since = now_ms
                elif now_ms - safe_recover_since >= 300:
                    ctrl.reset()
                    mode = "HOLD"
            else:
                safe_recover_since = None

        # ---------- control ----------
        if mode == "TASK3" and pos_cm is not None:
            # TASK3 runs its own controller against its own config; nothing in
            # this branch reads CONFIG or touches ctrl
            target_cm = fsm.step(pos_cm, v_cms, now_ms)
            stuck = t3.update(target_cm, pos_cm, v_cms, dt, now_ms)
            motor_out_deg = t3.theta_cmd
            omega_out_dps = t3.omega
            drive_motor(motor_out_deg, omega_out_dps, now_ms, t3cfg.CONFIG)
            if t3.limited and not warn:
                warn = "TRAVEL LIMIT"
            # overtime never releases the beam: the task asks the ball to end at
            # -5 cm and stay there, so the target stays latched and only the
            # display goes red
            if fsm.overtime and not alarm:
                alarm = "TASK3 OVERTIME (holding -5cm)"
            if stuck:
                release_motor()
                fsm.stop()
                ctrl.reset(theta_deg=motor_out_deg)
                mode = "IDLE"
                if not alarm:
                    alarm = "BALL STUCK -> STOP"
        elif mode == "HOLD" and pos_cm is not None:
            target_cm = 0.0
            st = ctrl.update(target_cm, pos_cm, v_cms, dt, now_ms)
            motor_out_deg = st["theta_cmd"]
            omega_out_dps = st["omega_dps"]
            drive_motor(motor_out_deg, omega_out_dps, now_ms, CONFIG)
            # Feed TASK3's trim observer from HOLD.  With arm_skip = 1 there is
            # no ARM stage left to measure the balance angle in, and this loop
            # is holding the ball at the same centre O against the same
            # mechanical zero offset -- different gains change the shape of the
            # limit cycle, not its mean.  Costs nothing when arm_skip = 0.
            t3.observe_trim(motor_out_deg, omega_out_dps)
            # the limiter fires briefly during any big move, so it is a live
            # indicator, not a latched fault -- otherwise it would stick on the
            # first big move and hide the faults that matter
            if st["limited"] and not warn:
                warn = "TRAVEL LIMIT"
            if st["stuck"]:
                # do not just complain: the beam is pinned against its stop with
                # the ball refusing to move, which is exactly the stall that
                # browns out the battery and resets the board.  Drop the load.
                release_motor()
                ctrl.reset(theta_deg=motor_out_deg)
                mode = "IDLE"
                if not alarm:
                    alarm = "BALL STUCK -> STOP"
        elif mode == "IDLE":
            omega_out_dps = 0.0

        # ---------- motor events ----------
        for ev in motor.poll():
            if isinstance(ev, tuple) and ev[0] == "pos":
                ctrl.note_measured_theta(ev[1])
                if mode == "IDLE":
                    # nothing is driving, so track the real pose; entering HOLD
                    # or TASK3 then starts from where the beam actually is
                    ctrl.theta_cmd = ev[1]
                    t3.theta_cmd = ev[1]
            elif ev == "e2" and motor.e2_streak >= 3:
                release_motor()
                motor.enable(True)
                motor.e2_streak = 0
                fsm.stop()
                ctrl.reset()
                mode = "IDLE"
                alarm = "MOTOR E2 x3 -> STOP"
            elif ev == "ee" and motor.ee_count >= 5:
                # one EE is a glitch on a noisy bus; a stream of them means the
                # frame format or the baud/checksum config really is wrong.
                # Threshold it so a single stray byte cannot latch the alarm and
                # mask the faults that matter.
                if not alarm:
                    alarm = "MOTOR EE x{} (bad frame)".format(motor.ee_count)

        # ---------- telemetry ----------
        # the internals come from whichever controller is actually driving, so
        # one CSV covers both modes and the columns keep the same meaning
        if mode == "TASK3":
            t_vref, t_omega, t_theta = t3.v_ref_cms, t3.omega, t3.theta_cmd
            t_vctrl, t_aest, t_lim = t3.v_est, t3.a_est, t3.limited
        else:
            t_vref, t_omega, t_theta = ctrl.v_ref_cms, ctrl.omega, ctrl.theta_cmd
            t_vctrl = ctrl.speed.v_est
            t_aest, t_lim = ctrl.vel.a_est, ctrl.limiter.active

        if TELEMETRY:
            if telem_t0 is None:
                telem_t0 = now_ms
            print("T,{},{},{},{:.2f},{},{:.2f},{:.2f},{:.2f},{:.3f},{:.1f},"
                  "{},{},{},{},{}".format(
                      now_ms - telem_t0, mode, loop_ms, target_cm,
                      "nan" if pos_cm is None else "{:.3f}".format(pos_cm),
                      t_vctrl, t_vref, t_omega, t_theta, t_aest,
                      1 if t_lim else 0,
                      motor.tx_count, motor.e2_count, motor.ee_count,
                      motor.rx_count))

        if PROFILE:
            # stamped AFTER the telemetry print on purpose: a CSV row per frame
            # is not free, and charging it to the draw column would point the
            # fix at the screen when the cost is the serial console.
            t_now = time.ticks_ms()
            prof["ctl"] += t_now - t_prof
            t_prof = t_now

        # ---------- draw ----------
        cam_fps = 0
        try:
            cam_fps = int(cam.fps())
        except Exception:
            pass
        loop_fps = 0 if loop_ms == 0 else int(1000 // loop_ms)
        eff_fps = min(cam_fps, loop_fps) if cam_fps > 0 else loop_fps

        if ui.mode == "run":
            task_result = None
            # The clock runs live from the moment the run starts, not just at
            # DONE: while the ball is moving the only question is "are we going
            # to make 5 s", and a number that appears afterwards cannot answer
            # it.  fsm.t0 is set the same frame the playback starts, so this is
            # the scored time, not the time since the button.
            task_time_s = None
            if fsm.state == Task3FSM.DONE and fsm.total_s is not None:
                task_time_s = fsm.total_s
            elif fsm.running and fsm.t0 is not None:
                task_time_s = (now_ms - fsm.t0) / 1000.0
            # before the clock exists, the same slot carries the prompt: the
            # two-press start is only usable if "which press am I on" is
            # readable from across the bench.
            task_prompt = None
            if fsm.state == Task3FSM.ARM:
                task_prompt = "ARMING"
            elif fsm.state == Task3FSM.READY:
                task_prompt = "START"
            if fsm.state == Task3FSM.DONE and fsm.total_s is not None:
                # both scored errors on screen next to the clock.  Without them
                # a run "looks fine" and you have no idea whether it scored.
                task_result = "+5:{:.2f} -5:{:.2f}".format(
                    fsm.err_pos_cm, fsm.err_neg_cm)
                out_of_spec = (fsm.total_s > t3cfg.TASK_LIMIT_S
                               or fsm.err_pos_cm > t3cfg.TASK_ERR_CM
                               or fsm.err_neg_cm > t3cfg.TASK_ERR_CM)
                if out_of_spec and not alarm:
                    alarm = "OUT OF SPEC (holding -5cm)"
        if not draw_now:
            pass
        elif ui.mode == "run":
            draw_axis_and_targets(img, target_cm)
            ui.draw_run(img, {
                "pos_cm": pos_cm if pos_cm is not None else 0.0,
                "target_cm": target_cm,
                "motor_deg": motor_out_deg,
                "omega_dps": omega_out_dps,
                "v_ref_cms": t_vref,
                "mode": mode,
                "sub": fsm.state if fsm.running else "",
                "fps": eff_fps,
                "ball_valid": pos_cm is not None,
                "task_time_s": task_time_s,
                "task_limit_s": t3cfg.TASK_LIMIT_S,
                "task_prompt": task_prompt,
                "task_prompt_ready": fsm.state == Task3FSM.READY,
                "task_result": task_result,
                "alarm": alarm,
                "warn": warn,
            })
        else:
            ui.draw_tune(img, now_ms)

        if draw_now:
            disp.show(img)

        if PROFILE:
            t_now = time.ticks_ms()
            prof["ui"] += t_now - t_prof
            prof["n"] += 1
            span = t_now - prof["since"]
            if span >= 1000:
                n = prof["n"]
                print("PROF {:2d}fps  相机{:.1f} 检测{:.1f} 控制{:.1f} "
                      "画面{:.1f} ms/帧  (画面分频 {})".format(
                          int(n * 1000 / span), prof["cam"] / n,
                          prof["det"] / n, prof["ctl"] / n, prof["ui"] / n,
                          int(CONFIG["draw_every"])))
                prof.update(n=0, cam=0, det=0, ctl=0, ui=0, since=t_now)
finally:
    # Task 3 requires the ball to still be sitting at -5 cm when the program
    # ends, so a run that reached TASK3 exits by HOLDING the last commanded
    # tilt with the motor still energised.  Returning to level -- the normal
    # exit below -- removes the trim that is keeping the ball there and it
    # simply rolls off.  Set task3_config.LEVEL_BEAM_ON_EXIT = True to override
    # when packing the rig up.
    hold_task3 = fsm.running and not t3cfg.LEVEL_BEAM_ON_EXIT
    try:
        if hold_task3:
            if t3cfg.CONFIG["drive_mode"]:
                # velocity mode has no position to hold: a bare stop would leave
                # the beam wherever inertia put it, so pin it with one absolute
                # frame at the angle the loop last commanded
                motor.move_abs_deg(t3.theta_cmd, 120,
                                   t3cfg.CONFIG["motor_acc"], force=True)
                time.sleep_ms(100)
            print("exiting: holding {:+.2f} deg, motor stays enabled, "
                  "ball parked at -5cm".format(t3.theta_cmd))
        else:
            print("exiting: beam back to level, motor stop")
            # velocity mode has no target to reach, so stop first, then walk the
            # beam back to level with an absolute move
            motor.stop_now()
            motor.reached_flag = False
            motor.move_abs_deg(0.0, 60, 200, force=True)
            t_exit = time.ticks_ms()
            while time.ticks_ms() - t_exit < 1500:
                motor.poll()
                if motor.reached_flag:
                    break
                time.sleep_ms(20)
            motor.stop_now()
    except Exception as e:
        print("shutdown error:", e)
    # after the motor, and outside its try: the beam is what must be left in a
    # defined state, but the lamp draws from the same battery and nothing is
    # left running to turn it off.  BoardLight swallows its own errors.
    light.off()
